baseURL = "https://sukyology.github.io/"
languageCode = "ko-kr"
title = "sukyology"
theme = "ananke"
resourceDir = "../resources"

DefaultContentLanguage = "ko"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "282819216"
enableRobotsTXT = true
#disqusShortname = "sukyology.github.io"


[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
favicon = ""
site_logo = ""
description = "석교의 블로그"
facebook = ""
twitter = "https://twitter.com/sukyology"
instagram = ""
youtube = ""
github = "https://github.com/sukyology"
gitlab = ""
linkedin = ""
mastodon = ""
slack = ""
stackoverflow = ""
rss = ""
# choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
featured_image = "/images/gohugo-default-sample-hero-image.jpg"
recent_posts_number = 2
